### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by snowkoan** [hasherezade/process_ghosting#10]
Hello,

Thanks for all your POCs. I'm interested in using process_ghosting to test some software. Would it be possible for you to add a license to this repo so that I don't run afoul of any copyright issues when modifying it, adding it to our test repository etc...

Many thanks.

**Comment by hasherezade** [comment]
Hi! sure, no problem. I will do it.

**Comment by snowkoan** [comment]
Thank you so much!
